name: Release strui

on:
  push:
    tags:
      - '**'

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make libunistring-dev

      - name: Build binary
        run: make BIN=build/strui-linux-x86_64

      - name: Package binary
        run: |
          TARGET=linux-x86_64
          mkdir -p dist/$TARGET
          strip build/strui-$TARGET
          tar -czf dist/$TARGET/strui-$TARGET.tar.gz -C build strui-$TARGET
          sha256sum dist/$TARGET/strui-$TARGET.tar.gz > dist/$TARGET/strui-$TARGET.sha256

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/linux-x86_64/strui-linux-x86_64.tar.gz
            dist/linux-x86_64/strui-linux-x86_64.sha256
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          