name: Release strui

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [linux-x86_64, linux-aarch64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          # TODO: Re-enable Windows target when libunistring is cross-built
          # sudo apt-get install -y gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64
          sudo apt-get install -y g++ make libunistring-dev \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu

      - name: Resolve compiler for ${{ matrix.target }}
        id: compiler
        run: |
          COMPILER=$(./scripts/resolve_compiler.sh ${{ matrix.target }})
          echo "compiler=$COMPILER" >> "$GITHUB_OUTPUT"

      - name: Build binary
        run: |
          mkdir -p build
          make BIN=build/strui-${{ matrix.target }} CXX=${{ steps.compiler.outputs.compiler }}

      - name: Package binary
        run: |
          TARGET=${{ matrix.target }}
          mkdir -p dist/$TARGET
          strip build/strui-$TARGET || true
          tar -czf dist/$TARGET/strui-$TARGET.tar.gz -C build strui-$TARGET
          sha256sum dist/$TARGET/strui-$TARGET.tar.gz > dist/$TARGET/strui-$TARGET.sha256

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/${{ matrix.target }}/strui-${{ matrix.target }}.tar.gz
            dist/${{ matrix.target }}/strui-${{ matrix.target }}.sha256
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

